/*  
 * Generated by the @fxs add utility, (c) Effix, France . 
 * 
 * (C) Copyright 1994 Effix SA, France, All Rights Reserved. 
 * 
 * $Log:	FormatComm.h,v $
 * Revision 1.11  2002/08/06  15:58:22  emmkimme
 * DEV:=K4.5.1, Drag/Drop and Copy/Paste revision (2)
 * 
 * Revision 1.10  2002/07/03  08:32:39  emmkimme
 * DEV:=K4.5.0, Drag/Drop and Copy/Paste revision
 * 
 * Revision 1.9  1998/11/05  11:18:24  ludpilla
 * DEV:=K2.1.1 + explicit export
 * 
 * Revision 1.8  98/09/15  11:44:30  ludpilla
 * DEV:=K2.1.0 + new iostreams
 * 
 * Revision 1.7  96/12/19  18:11:35  rachid
 * DEV:=K1.1.24 + fix mode
 * 
 * Revision 1.6  96/09/26  11:29:00  rachid
 * DEV:=K1.1.17 + interface change
 * 
 * Revision 1.5  96/07/17  18:22:45  rachid
 * DEV:=K1.1.9 + inheritance improvement
 * 
 * Revision 1.4  96/06/28  19:26:23  rachid
 * DEV:=K1.1.6 + NT corrections
 * 
 * Revision 1.2  96/06/05  17:46:22  rachid
 * DEV:=K1.1.2 + corrections
 * 
 * Revision 1.1  96/05/31  13:55:35  rachid
 * Initial revision
 * 
 * 
 */ 

/* "@(#) $Id: FormatComm.h,v 1.11 2002/08/06 15:58:22 emmkimme Exp $" */ 


#pragma once

/*----------      System and librairies headers     ----------*/ 


/*----------     Constant expressions definition    ----------*/ 


/*----------             Type definition            ----------*/ 


/*----------      Global variables declaration      ----------*/ 


/*----------        Global macros definition        ----------*/ 


/*----------      Extern functions declaration      ----------*/ 

class FormatCommunication
{
public:

  FormatCommunication (Format* fmt, int cid, int mode);
  ~FormatCommunication ();

  void write(LPDATAOBJECT pIDataObject, std::istream& is, HWND hwnd, int bufsize = 0);
  void read(LPDATAOBJECT pIDataObject, std::ostream& os, int* size, HWND hwnd);
  Format* format() const;
  int getKobraID() const;

  int cid() const;
  void cid(int);
  int mode() const;
  void mode(int);
  
private:
  Format* fmt_;
  int cid_;
  int mode_;
};
