#pragma once

template <class T>
class CProxy_IIGMenuBarDropButtonEvents : public IConnectionPointImpl<T, &__uuidof(_IIGMenuBarDropButtonEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
