#pragma once

template <class T>
class CProxy_IIGMenuBarEvents : public IConnectionPointImpl<T, &__uuidof(_IIGMenuBarEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
