#pragma once

template <class T>
class CProxy_IIGFrameEvents : public IConnectionPointImpl<T, &__uuidof(_IIGFrameEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
