#pragma once

template <class T>
class CProxy_IIGLayerManagerEvents : public IConnectionPointImpl<T, &__uuidof( _IIGLayerManagerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
