#pragma once

template <class T>
class CProxy_IIGMultiFrameEvents : public IConnectionPointImpl<T, &__uuidof(_IIGMultiFrameEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
