#pragma once

template <class T>
class CProxy_IIGWorkspaceEvents : public IConnectionPointImpl<T, &__uuidof( _IIGWorkspaceEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
