//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IGControls.rc
//
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 501
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 502
#define IDB_HORIZONTAL_SCROLLBAR_CHANNEL 503
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  504
#define IDB_HORIZONTAL_SCROLLBAR_THUMB_NO_COLOR 505
#define IDB_VERTICAL_SCROLLBAR_UPARROW  506
#define IDB_VERTICAL_SCROLLBAR_DOWNARROW 507
#define IDB_VERTICAL_SCROLLBAR_CHANNEL  508
#define IDB_VERTICAL_SCROLLBAR_THUMB    509
#define IDB_VERTICAL_SCROLLBAR_THUMB_NO_COLOR 510
#define IDD_SPLASH                      511
#define IDC_MESSAGE                     512
#define IDC_PROGRESS                    513
#define IDB_PROGRESS                    514
#define IDD_IGPROPERTYMANAGER           516
#define IDS_TITLEIGPROPERTYMANAGER      517
#define IDS_HELPFILEIGPROPERTYMANAGER   518
#define IDS_DOCSTRINGIGPROPERTYMANAGER  519
#define IDR_IGPROPERTYMANAGER           520

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        514
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         514
#define _APS_NEXT_SYMED_VALUE           521
#endif
#endif
