#pragma once

RGBQUAD CXIMAGEMIXING_ALPHA (RGBQUAD, RGBQUAD);
RGBQUAD CXIMAGEMIXING_DARKENING (RGBQUAD, RGBQUAD);
RGBQUAD CXIMAGEMIXING_MULTIPLY (RGBQUAD, RGBQUAD);
RGBQUAD CXIMAGEMIXING_SCREEN (RGBQUAD rgbqSrc, RGBQUAD rgbqDst);
RGBQUAD CXIMAGEMIXING_OVERLAY (RGBQUAD rgbqSrc, RGBQUAD rgbqDst);